### ISSUE TITLE
SyntaxError: missing = in const declaration (Firefox)

### ISSUE THREAD

**Issue by vishal-singhal** [sindresorhus/map-obj#11]
Index.js line 28 , const used in iterator for loop , should be let or var. It breaks in old browser (Firefox 46.0.1) with following error https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Errors/Missing_initializer_in_const

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
