### ISSUE TITLE
No documentation that there is no es5 build

### ISSUE THREAD

**Issue by 0xR** [sindresorhus/map-obj#14]
I have to transpile this package to make it useable for IE11. Maybe you could provide two build targets?

Or at least state clearly in the README that it is not es5.

**Comment by sindresorhus** [comment]
I state the target in https://github.com/sindresorhus/map-obj/blob/4db51b6f5f6d2b617bc80bb66dd6a6e528dc4cb7/package.json#L13 I build for Node.js. All my modules require transpilation for the use in the browser.

**Comment by sindresorhus** [comment]
You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
