### ISSUE TITLE
Access to parent key

### ISSUE THREAD

**Issue by jneuendorf** [sindresorhus/map-obj#17]
Hey,

I have a use case where I don't map keys but values.
It would be useful for me to be able to access the parent's key (which is unchanged in my case) or even a list of all parents, grand-parents etc.

I realize that when mapping keys this may not make much sense but I also think there could be use cases.

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but it's outside the intended scope of this package.

**Comment by gajus** [comment]
If anyone knows a package that fulfills this need, I would appreciate a link. I've landed on this limitation many times...
