### ISSUE TITLE
allow falsy return value as a sort of "filter" 

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/map-obj#2]
If they return a falsie value, skip this key/value pair.

It might be safest if you make them explicitly return a specific value(`false` or `null`), to guard against accidental returns of `undefined`.

**Comment by sindresorhus** [comment]
I don't think this is a good idea. `map` is well known as mapping 1:1. I think this would be weird. Also a reason array have both `.map` and `.filter`.

See https://github.com/sindresorhus/filter-obj for filtering.
