### ISSUE TITLE
Provide dot-prop-like keys

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/map-obj#28]
Useful for pinpointing exactly where a key is in an object. Useful to determine where a key is located in a deep object:

```js
const mapObject = require("map-obj")

mapObject({
	a: {
		b: "🦄"
	}
}, (key, value) => {
	console.log(key)

	return [key, value]
}, {
	deep: true,
	dotPropKeys: true
})
//=> "a"
//=> "a.b"
```

**Comment by sindresorhus** [comment]
What would you use the key path for? Debugging? Not sure I see the real-world use-case for this.

**Comment by Richienb** [comment]
I'm maintaining a library that transforms values in an object unless it is located somewhere within it.

**Comment by sindresorhus** [comment]
It's still unclear to me how you would use this information. What would you do with a string `a.b`?

Some other concerns:

- I don't think an option should change what `key` means. If this were to be added, it should rather be a method like `mapObj.keyPath(key) //=> 'a.b'`.
- This feels a bit niche. Maybe it would be better as a utility method on https://github.com/sindresorhus/dot-prop ?

**Comment by sindresorhus** [comment]
I'm going to close this in favor of:

> Maybe it would be better as a utility method on sindresorhus/dot-prop ?
