### ISSUE TITLE
`__proto__` keys assign to the prototype

### ISSUE THREAD

**Issue by ninevra** [sindresorhus/map-obj#33]
If a mapper function produces `['__proto__', value]`, rather than create a corresponding own property, `mapObject` sets the prototype of the target object to the output value.

This prevents objects containing `__proto__` keys from round-tripping through the identity function, and prevents mappers from producing `__proto__` keys.

One possible fix is to use `Object.defineProperty()` for creating properties, rather than assignment. However, this would also change `mapObject`'s behavior in certain edge cases when given custom `target` objects: their setters would not invoked, their non-writable own properties would be overwritten with writable properties, and writable non-configurable own properties would throw `TypeError`s. Would that be considered a breaking change?

I'll submit a PR adding failing test cases.

**Comment by sindresorhus** [comment]
Your proposed solution is probably the technically best one, but `map-obj` is quite popular and I'm paranoid about making subtle changes to it, even through a major version. What do you think about just filtering out the `__proto__` key?

**Comment by ninevra** [comment]
> What do you think about just filtering out the `__proto__` key?

Makes sense to me. That'd technically still violate the documented API, but it'd prevent the more confusing consequences of this bug without changing the behavior of any currently-working code.

Another option would be to throw an error if the mapper outputs `__proto__` keys. That would be similarly non-breaking and would make sure no-one receives technically-incorrect output; but I guess it could potentially be a DoS hazard?

**Comment by sindresorhus** [comment]
> Another option would be to throw an error if the mapper outputs __proto__ keys. That would be similarly non-breaking and would make sure no-one receives technically-incorrect output; but I guess it could potentially be a DoS hazard?

I don't think throwing is the right choice here. Setting `__proto__` is always the wrong choice, so I cannot imagine any valid scenario doing it, but I also don't want to crash someones process over it.
