### ISSUE TITLE
Add ability to remove a key

### ISSUE THREAD

**Issue by gr2m** [sindresorhus/map-obj#36]
Would you accept a pull request which implements the following?

```js
mapObject({one: 1, two: 2}, (key, value) => value === 1 ? [key, value] : null);
//=> {one: 1}
```

The code change will look like this

```diff
-let [newKey, newValue, {shouldRecurse = true} = {}] = mapper(key, value, object);
+let mapResult = mapper(key, value, object)
+if (mapResult === null) continue
+let [newKey, newValue, {shouldRecurse = true} = {}] = mapResult
```

**Comment by brandon93s** [comment]
Even with `Symbol('skip')` wouldn't we need to support an `options.filter` function, unless we expect consumers to pre-apply the symbol to entries?  A `filter` function could more broadly remove records, based on consumer use-case, by either key or value.

**Comment by gr2m** [comment]
@brandon93s Maybe I misunderstood what you mean, but I don't think it's true. Returning `mapObject.mapObjSkip` instead of the `[key, value]` array will remove the key from the object, no further filtering is necessary

See my pull request at https://github.com/sindresorhus/map-obj/pull/38
