### ISSUE TITLE
Throw error on Arrays.

### ISSUE THREAD

**Issue by rocktimsaikia** [sindresorhus/map-obj#39]
The library is not supposed to accept arrays. And it does not throw any errors on passing one too.

```js
const newObj = mapObject([2, 1], (key, value) => [value, key]);

console.log(newObj)
//=> outputs
[ 2, 1 ]

```
This is due to this check. Since arrays are objects too, It lets them slide in.
https://github.com/sindresorhus/map-obj/blob/1e5c466ee0f293e91465ecd53d74ecdeb90cb4e4/index.js#L3
<br/>
We can use the [is-plain-obj](https://github.com/sindresorhus/is-plain-obj) package here to check only plain objects and update the docs to clearly specify that this lib is only for `plain objects`.

**Comment by sindresorhus** [comment]
I don't think we should limit it to plain objects. There are valid use-cases for mapping from non-plain objects. I do agree we should not allow arrays though.

**Comment by rocktimsaikia** [comment]
Right. Make sense. I will add a PR for the array issue.
