### ISSUE TITLE
SyntaxError: missing = in const declaration

### ISSUE THREAD

**Issue by liubko** [sindresorhus/map-obj#5]
https://github.com/sindresorhus/map-obj/blob/master/index.js#L28

this line causes an error in Firefox v49.0.1

**Comment by sindresorhus** [comment]
That's a Firefox bug in their `const` implementation.

**Comment by liubko** [comment]
_True, but making a workaround here is much faster than waiting for a fix in firefox. Anyway, it's up to you._
