### ISSUE TITLE
browserify

### ISSUE THREAD

**Issue by parro-it** [sindresorhus/map-obj#7]
I know you don't want to publish babelified versions of your module, and you prefer your users takes care of that.

But in order to do that, I have to manually change `map-obj` package.json every time I deploy, to add:

```js
"browserify": {
    "transform": [
      "babelify"
    ]
  }
```

would you accept a PR to add that code to pkg file?

**Comment by sindresorhus** [comment]
No. Sorry for the trouble, but I'm not going to start doing that now. You're also going to hit more and more packages going forward that requires transpilation.

See: https://github.com/sindresorhus/ama/issues/446

If you had used Webpack, you could have used [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled. Maybe worth making something similar for Browserify.

**Comment by parro-it** [comment]
Thank you anyway, @sindresorhus, and no worries!
I'll think of another way to automate my build process... I hope I won't have to fork map-obj itself

**Comment by sindresorhus** [comment]
https://www.npmjs.com/package/%40atomic-app%2Fmap-obj

**Comment by parro-it** [comment]
Awesome! Thank you!
